development:
  adapter: postgresql
  encoding: unicode
  database: morale_up_dev
  pool: 5
#  username: myapp
#  password: password1

test:
  adapter: postgresql
  encoding: unicode
  database: morale_up_test_me
  pool: 5
 # username: myapp
 # password: password1
